apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmd-deploy
  namespace: default
spec:
  ## Set to 5 for start
  replicas: 5
  selector:
    matchLabels:
      env: wmd
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        env: wmd
    spec:
      containers:
        - name: wmd-ctr
          image: kaiwalyakoparkar/wemakedevs:1.0
          ports:
            - containerPort: 3000
